import imgHero from "./image/Hero1.png"
import imgHero2 from "./image/Hero2.png"
import imgHero3 from "./image/Hero3.png"
import imgAboutUs from "./image/AboutUs.png"
import imgAbout from "./image/About.png"
import imgNangis from "./image/nangis1.png"
import imgNangis2 from "./image/nangis2.png"
import imgNangis3 from "./image/nangis3.png"
import imgDokter1 from "./image/Dokter1.jpg"
import imgDokter2 from "./image/Dokter2.jpg"
import imgDokter3 from "./image/Dokter3.jpg"
import imgFaq from "./image/Faq.jpeg"
import imgFacebook from "./image/Facebook.png"
import imgGoogle from "./image/google.png"
import imgLogin from "./image/loginn.png"
import imgRegister from "./image/Register.png"
import imgLDokter1 from "./image/ListDokter1.jpg"
import imgLDokter2 from "./image/ListDokter2.jpg"
import imgLDokter3 from "./image/ListDokter3.jpg"
import imgLDokter4 from "./image/ListDokter4.jpg"
import imgLDokter5 from "./image/ListDokter5.jpg"
import imgLDokter6 from "./image/ListDokter6.jpg"
import imgLDokter7 from "./image/ListDokter7.jpg"
import imgLDokter8 from "./image/ListDokter8.jpg"

export {imgRegister ,imgLogin, imgHero , imgHero2 , imgHero3, imgAboutUs,imgAbout, imgNangis , imgNangis2 ,imgNangis3,imgDokter1 , imgDokter2, imgDokter3 , imgFaq , imgFacebook , imgGoogle , imgLDokter1, imgLDokter2, imgLDokter3, imgLDokter4,imgLDokter5,imgLDokter6,imgLDokter7,imgLDokter8}